Explaining what the [extras] in Nikola[extras] is about.
getnikola/nikola-site pull request #44
Opened 2024-01-05 22:23 UTC by aknrdureegaesr

The other day, Chris invested the patience to explain to me (via IRC) what the `[extras]` in `Nikola[extras]` is about. In appreciation of his effort and that put in by everybody on the Nikola team, I suggest this change of documentation, which puts Chris' answer where more people can benefit from it.

2024-01-06 10:41 UTC, Kwpolska reviewed
Good, but could use some stylistic improvements.

2024-01-06 10:41 UTC, Kwpolska commented on stories/getting-started.html
> +    <h3 id="extras_explained">What is this [extras]?</h3>
1. Please place the section at the end of Step 1, after “Other options”.
2. Please use camelCase for the IDs for consistency (`extrasExplained`).

2024-01-09 16:34 UTC, aknrdureegaesr commented on stories/getting-started.html
> +    <h3 id="extras_explained">What is this [extras]?</h3>
I believe I have done these two things. Please kindly re-review.

2024-01-09 22:08 UTC, Kwpolska requested changes

2024-01-09 22:08 UTC, Kwpolska commented on stories/getting-started.html
> +<div class="col-md-12">
This shouldn’t be a standalone section, please put it before line 120 (so that it appears to the left of the install instructions).

2024-01-11 10:16 UTC, aknrdureegaesr commented on stories/getting-started.html
> +<div class="col-md-12">
I tried that, and it looks wrong to me.

* This isn't an install instruction for a particular platform any more. So it is just as well if it starts a new visual block.
* On the other hand, this isn't a new step by itself. It is more of a footnote of the "general instructions". There is also a link from the general instructions to the new material. So we want a bit of visual separation from Windows / mac os / distro packages, but a new '<h2>` block is clearly not warranted. If find starting a new standalone section is just the ticket.
* A minor issue: Screen width is good for the message text sample, to avoid the horizontal scrollbar.

2024-01-11 20:11 UTC, Kwpolska commented on stories/getting-started.html
> +<div class="col-md-12">
The install section also includes details about Windows support or extension building issues — it’s all things “installing”.

2024-01-16 11:06 UTC, aknrdureegaesr commented on stories/getting-started.html
> +<div class="col-md-12">
I'm not totally convinced that is the best way to organize this, but it is a way. And I am totally convinced meticulously discussing this fine point is not worth both your and my time. Ok, so I've done it as you've wanted (or believe that's what I did, at least). Also rebased to recent `master`

2024-01-16 22:51 UTC, Kwpolska approved these changes

2024-01-16 22:51 UTC, merged

2024-01-16 22:53 UTC, Kwpolska commented
Thanks, merged and deployed!